---
- name: configure stackit server
  hosts: servers
  become: yes

  tasks:
    - name: update system packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: add ec2-user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes